[supabase]
url = "https://htyokbakmpezvyocfopj.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0eW9rYmFrbXBlenZ5b2Nmb3BqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NjA3ODIsImV4cCI6MjA1NTIzNjc4Mn0.p23Vfi3IuR4gr4Rwk2h6M_iSsM_GbCkipBG0p5vZ_aM"
[polygon]
api_key="kBEqnbsNaBWIfRkZqhS_RXbTjJVu88Ds"
